[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"

[deploy]
startCommand = "npm start"
healthcheckPath = "/api/latex/health"
healthcheckTimeout = 100
restartPolicyType = "on_failure"

[environments.production]
variables = { NODE_ENV = "production" }