[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile"
watchPatterns = ["everleaf-backend/**"]

[deploy]
numReplicas = 1
sleepApplication = false
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
startCommand = "npm start"
healthcheckPath = "/api/latex/health"
healthcheckTimeout = 300
healthcheckInitialDelay = 60

[environments.production]
variables = { NODE_ENV = "production" }

[environments.development]
variables = { NODE_ENV = "development" }

# Increased resource allocation for TexLive
[resources]
memoryGB = 4
vCPU = 2

# Build configuration for Railway
[build.env]
DEBIAN_FRONTEND = "noninteractive"
TEXLIVE_INSTALL_NO_CONTEXT_CACHE = "1"